# Use root/example as user/password credentials
version: '3.8'
services:
  db:
    image: mongo
    container_name: db
    hostname: db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "dbdata:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  dbadmin:
    image: mongo-express
    depends_on:
      - db
    container_name: dbadmin
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/

  server:
    build: ./server
    depends_on:
      - db
      - dbadmin
    container_name: server
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_PORT: 3000
      MONGO_URI: mongodb://root:example@db:27017/

volumes:
  dbdata: